version: "3.9"

services:
  user-db:
    image: postgres:alpine
    container_name: ceramic-user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  auth-db:
    image: mysql:latest
    container_name: ceramic-auth-db
    environment:
        MYSQL_ROOT_PASSWORD: auth_pass
        MYSQL_DATABASE: auth_db
        MYSQL_USER: auth_user
        MYSQL_PASSWORD: auth_pass
    ports:
      - "3306:3306"
    volumes:
      - auth-db-data:/var/lib/mysql

  user-service:
    depends_on:
      - user-db
      - discovery-service
    restart: always
    build: /backend/user-service
    container_name: user-service

  auth-service:
    depends_on:
      - auth-db
      - discovery-service
    restart: always
    build: /backend/auth-service
    container_name: auth-service

  discovery-service:
    restart: always
    build: /backend/discovery-service
    container_name: discovery-service

  api-gateway:
    depends_on:
      - discovery-service
    restart: always
    build: /backend/api-gateway
    container_name: api-gateway
    ports:
      - "4020:4020"


volumes:
  user-db-data:
  auth-db-data: