version: "3.9"

services:
  user-db:
    image: postgres:alpine
    container_name: ceramic-user-db
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: user_db
    ports:
        - "5432:5432"
    volumes:
        - user-db-data:/var/lib/postgresql/data

  user-service:
    depends_on:
      - user-db
      - discovery-service
    restart: always
    build: /backend/user-service
    container_name: user-service

  discovery-service:
    restart: always
    build: /backend/discovery-service
    container_name: discovery-service

  api-gateway:
    depends_on:
      - discovery-service
    restart: always
    build: /backend/api-gateway
    container_name: api-gateway
    ports:
      - "4020:4020"


volumes:
  user-db-data: