version: "3.9"

services:
  user-db:
    image: postgres:alpine
    container_name: ceramic-user-db
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: user_db
    ports:
        - "5432:5432"
    volumes:
        - user-db-data:/var/lib/postgresql/data

  user-service:
    depends_on:
      - user-db
      - discovery-service
    restart: always
    build: /backend/user-service
    container_name: user-service
    ports:
      - "4011:4011"

  discovery-service:
    restart: always
    build: /backend/discovery-service
    container_name: discovery-service
    ports:
      - "4050:4050"

volumes:
  user-db-data: