spring.application.name=api-gateway

server.port=4020

eureka.client.service-url.defaultZone=http://discovery-service:4050/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[2].id=product-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/products/**

